### ISSUE TITLE
error when running dockerd

### ISSUE THREAD

**Issue by devomaa** [docker/for-linux#1020]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
for the docker daemon to be running

### Actual behavior
crashes, [heres the log](https://pastebin.com/rsQMdd52)

### Steps to reproduce the behavior
run `dockerd` (probably just my laptop)

**Output of `docker version`:**

```
Client:
 Version:           19.03.9-ce
 API version:       1.40
 Go version:        go1.14.3
 Git commit:        9d988398e7
 Built:             Tue May 19 22:11:18 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.soc: dial unix /var/run/docker.sock: connect: permission denied
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
ERROR: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.40/info": dial unix /var/run/docker.sock: connect: permission denied
errors pretty printing info
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
I am running Arch Linux, heres my `uname -a` output:
`Linux no 5.6.13-arch1-1 #1 SMP PREEMPT Thu, 14 May 2020 06:52:53 +0000 x86_64 GNU/Linux`

**Comment by thaJeztah** [comment]
The `/var/run/docker.sock` socket requires either `root` / `sudo` or the current user to be in the `docker` group (see https://docs.docker.com/engine/install/linux-postinstall/).

A user having access to the docker remote API (which the docker socket provides) is equivalent to having `root` access on the machine (see [Docker daemon attack surface](https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface)), and for that reason has stricter permissions set.

Note that Arch linux is not officially supported (docker does not provide official packages for that distribution); if you installed the `docker` package from the Arch Linux package repository, those packages are maintained and built by the Arch linux package maintainers, and could have other changes; for further assistance, it's best to open a ticket in the Arch linux issue tracker.

Closing this issue here because of the above, but feel free to continue the conversation
