### ISSUE TITLE
docker daemon command does not work in 17.06, target for removal in 17.12

### ISSUE THREAD

**Issue by StefanScherer** [docker/for-linux#11]
### Expected behavior

The command "docker daemon ..." starts the Docker engine.

### Actual behavior

```
$ docker daemon
`docker daemon` is not supported on Linux. Please run `dockerd` directly
```

### Information

Just wondering why the command `docker daemon` doesn't work in 17.06.0-ce-rc2 as https://docs.docker.com/engine/deprecated/#docker-daemon-subcommand tells me that it will be removed in 17.12:

> docker daemon subcommand
> Deprecated In Release: v1.13.0
> 
> Target For Removal In Release: v17.12
> 
> The daemon is moved to a separate binary (dockerd), and should be used instead.

I encountered that problem while connecting an existing Ubuntu Xenial VM with Docker 17.06.0-ce-rc2 installed with `docker-machine` to insert TLS certs and restart the engine. 

I have fixed docker-machine with https://github.com/docker/machine/pull/4128 to switch over to "dockerd" for all CE versions.

The deprecation page should be updated.

### Steps to reproduce the behavior

  1. Create an Azure VM with Ubuntu Xenial
  2. Install Docker 17.06.0-ce-rc2
  3. `docker-machine create -d generic --generic-ip-address 1.2.3.4 --generic-ssh-user me azure1706`

**Comment by dnephin** [comment]
The client has to be built with the `daemon` tag to support the`docker daemon` subcommand. It looks like we aren't setting that by default right now.

**Comment by narration-sd** [comment]
You are very correct that this is wrong in a fresh 17.06.0, upgraded from fairly recent version.  It just cost me hours.

The problem seems to be that  the /etc/systemd/system/docker.service.d/10-machine.conf file still calls `docker daemon`. Thus the docker daemon doesn't start. 

The log messages suggested through sysctl docker status or journalctl -xe are completely useless, as they just say failed to start Docker Application ...etc.. This also should be fixed, or replaced with advice as to where to actually see a log that has the true failures, as otherwise your implementing community is flying entirely blind.

I fixed the problem by changing the conf file to reference dockerd. _Finding_ this was a nightmare. All kinds of specious results from docker-machine remotely, etc.. Another problem area to be sure, as it suggests you regenerate certs when the real problem is that the connection is refused at port 2376 -- since again, the daemon isn't running. I ask you. 

If you apt remove this 17.06.0 docker, delete I think this conf  directory, and then add it again, Docker will start and run previous  containers after the install. Once. It will not restart if stopped. Thus the regenerate certs for example will kill the machine, leaving blind again why that happened.

Really, you guys have to do better than this. Community edition forked or not, this has been the Docker way for years. I understand all about racing to a market, and thinking most trying your stuff aren't gurus, so who cares, but you're not going to get further than a starting line this way. 

/s/ not exactly not a guru

**Comment by eyeinsky** [comment]
Apparently, if you're creating a docker machine on a remote ubuntu box with the generic driver, docker reinstalls itself replacing a fixed `/etc/systemd/system/docker.service.d/10-machine.conf`. A solution-- if you don't actually care about the version --is to install docker from ubuntu's own repositories. These work.

**Comment by StefanScherer** [comment]
I've tested it with docker-machine 0.12.1 with an Ubuntu VM running in Azure ( `docker-machine create -d generic --generic-ip-address 1.2.3.4--generic-ssh-user me lin-01` ) and it now uses the `dockerd` command instead of `docker daemon`

Still wondering about the deprecation notice in the docs vs. the reality.

**Comment by eyeinsky** [comment]
@StefanScherer I don't think the docker-machine command itself matters (I didn't upgrade it on the computer I'm controlling the daemon from). It's the docker's systemd service on the server from docker-ce v17.06 which calls the non-existent `/usr/bin/docker daemon` command.

**Comment by StefanScherer** [comment]
In this case the version 0.12.1 matters as docker-machine did a wrong version check and thought a 17.0x is a very old version that only supports `docker daemon` command. It is fixed in 0.12.1.

**Comment by eyeinsky** [comment]
So maybe there are two issues? I installed docker on the server by actually ssh'ing into it and using the instructions in the docker docks. This installed the latest version and didn't work. Then I uninstalled that, and used apt instead (which installs 1.12.6), which worked.

Do you mean that if I hadn't done any manual installation and used docker-machine 0.12.1 then it would have pulled in the correct version?

But given that one *can* do a manual install, shouldn't the latest daemon come with dockerd still?

**Comment by joshuacox** [comment]
```
# apt install docker-ce
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  docker-ce
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 20.5 MB of archives.
After this operation, 96.2 MB of additional disk space will be used.
Get:1 https://download.docker.com/linux/ubuntu xenial/stable amd64 docker-ce amd64 17.06.0~ce-0~ubuntu [20.5 MB]
Fetched 20.5 MB in 0s (25.1 MB/s)
Selecting previously unselected package docker-ce.
(Reading database ... 582126 files and directories currently installed.)
Preparing to unpack .../docker-ce_17.06.0~ce-0~ubuntu_amd64.deb ...
Unpacking docker-ce (17.06.0~ce-0~ubuntu) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for systemd (229-4ubuntu17) ...
Processing triggers for ureadahead (0.100.0-19) ...
ureadahead will be reprofiled on next reboot
Setting up docker-ce (17.06.0~ce-0~ubuntu) ...
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2017-07-18 10:30:35 CDT; 3ms ago
     Docs: https://docs.docker.com
  Process: 8864 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 8864 (code=exited, status=1/FAILURE)

Jul 18 10:30:35 stealth systemd[1]: Failed to start Docker Application Container Engine.
Jul 18 10:30:35 stealth systemd[1]: docker.service: Unit entered failed state.
Jul 18 10:30:35 stealth systemd[1]: docker.service: Failed with result 'exit-code'.
dpkg: error processing package docker-ce (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (229-4ubuntu17) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

same here in ubuntu Xenial

**Comment by manast** [comment]
yeah, this is a really irritating issue. Unbelievable. A recreation of the machine did not work for me either. Lets hope if I can find dockerd to setup the systemd configuration manually...

**Comment by eyeinsky** [comment]
@manast If you don't require features from the newest version then just install docker from ubuntu's own repository!

**Comment by manast** [comment]
@eyeinsky it breaks my workflow. Anyway, upgrading to docker-machine 0.12.1, cleaning the target machine from docker's systemd scripts, and recreating the machine did the trick :).

**Comment by joshuacox** [comment]
This seems to be sweeping across many distros, got the same in arch recently as well.

**Comment by cpuguy83** [comment]
@eyeinsky The actual docker package does not create `/etc/systemd/system/docker.service.d/10-machine.conf`, this is 100% docker-machine doing this and should be fixed in 0.12.1 of docker-machine.

**Comment by StefanScherer** [comment]
Closing this as my use case is fixed in docker-machine 0.12.1. I hope other deprecation promises are more reliable in the future as it helps the community to adjust their tools/interfaces in time and not just after some features have been removed.

**Comment by FX-HAO** [comment]
Replace this line in `/etc/systemd/system/docker.service` and then run `systemctl daemon-reload` should fix the problem.
```
# ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=generic  --mtu=1472 --bip=10.1.63.1/24
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=generic  --mtu=1472 --bip=10.1.63.1/24
```

**Comment by kujiy** [comment]
This happened when upgraded a stand-alone `docker-engine:amd64 17.05.0~ce-0~ubuntu-xenial` to ` docker-ce:amd64 17.10.0~ce-0~ubuntu` on ubuntu 16. I removed docker-engine before [the procedure along the instruction](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/) but happened.

```sh
cat /etc/systemd/system/docker.service | grep ExecStart
#ExecStart=/usr/bin/docker daemon -H fd://
ExecStart=/usr/bin/dockerd -H fd://                   # <- I changed to this
```

It might not have happened if I executed `apt-get purge docker-engine` but I couldn't do it because I feard to lose `/var/lib/docker`. Anyway, thanks @FX-HAO 👍

**Comment by Forage** [comment]
I just now had the same issue, but I had to make the same change to the file `/etc/systemd/system/docker.service.d/docker-tcp.conf` on Ubuntu 17.10.
