### ISSUE TITLE
linux/static/edge/x86_64/docker-19.03.14.tgz missing

### ISSUE THREAD

**Issue by limetech** [docker/for-linux#1159]
* [ ] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

Forgive me if wrong place to report/ask about this.  Wondering if you guys are going to continue to produce the static binaries for Linux in https://download.docker.com/linux/static/edge/x86_64/

**Comment by quite4work** [comment]
I have the same Issue. 

It is likely a bug because `docker-19.03.14.tgz` is aviable for `stable` and `testing` but not for `edge`.

**Comment by thaJeztah** [comment]
Edge releases were deprecated starting with Docker 18.06 (see https://www.docker.com/blog/extending-support-cycle-docker-community-edition/), so I would recommend switching to either "testing" (GA + Beta + Release-Candidates) or "stable" (only GA releases).

Packages were pushed to edge channels for some time to give users some time to update to the other channels, but that will no longer be the case going forward. (I should add that the plan was to stop this with docker 20.10, but parts of the release pipeline could not be separated for the 19.03.x releases only, so it stopped slightly before that).

Let me close this issue because of the above, but feel free to continue the conversation
