### ISSUE TITLE
docker pull does not know how to resume previous failed attempt

### ISSUE THREAD

**Issue by jchia** [docker/for-linux#1187]
* [x] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
When a first attempt to `docker pull` an image fails after it has partial downloaded some data, a subsequent attempt should not start from scratch but resume the download from wherever the previous attempt failed. This way, when downloading an image that is large relative to network reliability, there is a high-enough probability of `docker pull` succeeding within a reasonable number of attempts.

### Actual behavior
Subsequent `docker pull` attempts start from scratch even if a previous attempt has "pull complete" for some layers. This means that for a large image and an intermittently failing connection, the chance of `docker pull` completing within a reasonable number of tries approaches zero as the image size increases. Consequently, this behavior can be considered to be a usability bug.

```
$ docker pull xilinx/vitis-ai:latest
latest: Pulling from xilinx/vitis-ai
f22ccc0b8772: Pull complete 
3cf8fb62ba5f: Pull complete 
e80c964ece6a: Pull complete 
afd3e84ff233: Pull complete 
caba11bf89c1: Pull complete 
21ff7ffad7fb: Pull complete 
0a1fb73e7f8f: Pull complete 
b700632d3b49: Pull complete 
f32b167b0bc9: Pull complete 
d5dca61bcafa: Pull complete 
bb15414437e3: Pull complete 
e73de575fa84: Pull complete 
b1a14839c8e3: Pull complete 
75052f7c411f: Pull complete 
e6c777df29dc: Pull complete 
741b871f4d0b: Pull complete 
bd09e2cec15d: Pull complete 
49359a403f15: Pull complete 
3dc515bfbb5a: Pull complete 
705cf80df2f3: Pull complete 
53d1bd56d0d4: Pull complete 
d2572bf03a3f: Pull complete 
c970ce782924: Pull complete 
b18006f4f833: Pull complete 
7dc2ec620aa4: Pull complete 
31cda23c4bce: Pull complete 
c4a6256a9c1b: Downloading [==================================================>]  3.801GB/3.801GB
b0190525f152: Download complete 
b44b92ba8003: Download complete 
ab4ebe064c35: Download complete 
unexpected EOF
$ docker pull xilinx/vitis-ai:latest
latest: Pulling from xilinx/vitis-ai
f22ccc0b8772: Downloading [======================================>            ]  20.56MB/26.71MB
...
```

### Steps to reproduce the behavior
1. `docker pull xilinx/vitis-ai:latest`
2. Ctrl-C after download finishes for some layer (simulating network failure).
3. `docker pull xilinx/vitis-ai:latest` and see that it starts from scratch.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Oct 14 19:43:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Oct 14 16:41:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 43
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-47-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.29GiB
 Name: frodo
 ID: KMLP:N2DN:SFDB:3AH4:ATYJ:6TUE:JKWM:SNY5:MHPT:LTG4:KJIW:CGWE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Ubuntu 20.04.1 LTS

**Comment by mika-cn** [comment]
I also met this problem. In my case there was no space left on device. But after the command failed, I checked my disk usage and it was not full. So the `docker pull` command will delete all downloaded bytes when it's execution fails?

I also noticed that the `docker pull` command can do incremental downloads. If the command keeps the last downloaded result. The next execution can continue from where the last execution failed rather than download everything again. 

Belowing is my case:

```
$ docker pull someImage

d8d02d457314: Pull complete 
aedaaab71de6: Pull complete 
6dd0b11147d1: Downloading [==================================================>]  161.6MB/161.6MB
9ad552f1001e: Download complete 
c0436fc23e5b: Download complete 
dc5b4c232dbb: Download complete 
write /var/lib/docker/tmp/GetImageBlob965483379: no space left on device
```

**Comment by Cartman0** [comment]
hi, i also want this feature such as `curl -C`, `wget -c`

**Comment by Cartman0** [comment]
we may be able to "resume" by saving temp of each image-layer.

**Comment by shakibamoshiri** [comment]
I already thought docker has this feature, till I tested it manually and realized there is no such a feature.  
Is there anything we should enable? An option or configuration?  
Or any version which after that we can have this feature?  
For people who have slow network this is super useful.

**Comment by jspilinek** [comment]
I ran into this issue recently. I was trying to pull Oracle 19c database which includes a 3GB file. It kept timing out after downloading 500MB to 1GB. I think something was going on with my internet connection that day. It eventually worked after attempting to pull about 8 times. Very frustrating that there's no option to resume the download.

**Comment by rajanant** [comment]
Extremely super useful feature

**Comment by chrisbward** [comment]
Insane

**Comment by Nefcanto** [comment]
So, is this implemented now?

**Comment by knusbaum** [comment]
This would be extremely helpful.

Pulling an image from docker hub that had many layers kept hanging for me today. Because it didn't resume and keep the successfully-downloaded layers, I had to retry several dozen times. Each time some random layer (or two) would hang. This is especially annoying and time consuming when the image contains lots of large layers, where each pull operation pulls a GB or more before failing.

**Comment by cpuguy83** [comment]
This will be in the next version of Docker.
Specifically you'll need to enable the containerd storage backend (which is/will-be opt-in) to support retries.
Also docker-desktop should have this today if you enable the experimental containerd storage backend.

I'm going to close this for house-keeping purposes since this work is already merged upstream.
Give it a try!

**Comment by Nefcanto** [comment]
@cpuguy83 Sorry to reopen this again. Please guide us more. Where are the docs regarding this? At least give us a link. How should we do it on Linux? What steps should I take in my `Dockerfile` or Docker Hub account, or in the `docker` command or anywhere else to enable it and use it? Please give us more information. Thanks.

**Comment by cpuguy83** [comment]
On Linux when using a build from HEAD, add this to dockerd's command line arguments: `--features='{"containerd-snapshotter": true}'`. Then whatever is passed to `--storage-driver` will be interpreted as a containerd snapshotter rather than a docker graphdriver. Regardless though, this enables pulling using containerd, which supports restarting from a partial pull.

In Docker Desktop, in `settings>features in development`, select "use containerd for pulling and storing images"

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/799078/223494725-a729f282-31e9-4ea3-8064-c26040403834.png">

Blog post: https://www.docker.com/blog/extending-docker-integration-with-containerd/

**Comment by mpeschel10** [comment]
Hi. I am on Arch Linux with docker 24.0.2. I was not able to make the `--features` flag work on my system. I tried changing the ExecStart line of /usr/lib/systemd/system/docker.service, but `systemctl start docker` would fail. `journalctl -u docker` gave "Status: unknown flag: --features".

However, I was able to enable `docker pull` to resume interrupted downloads by adding `"features": {"containerd-snapshotter": true}` to `/etc/docker/daemon.json`.
```sh
sudo mkdir /etc/docker
sudo gedit /etc/docker/daemon.json
```

Then make it look like:
```
{
    "features": {"containerd-snapshotter": true}
}
```
And restart docker.
```
sudo systemctl restart docker
```
[Link to config file documentation.](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file)

**Comment by mpeschel10** [comment]
Hi @cpuguy83,

I have edited my comment so that it no longer directly contradicts yours. I
am sorry I phrased it passive-aggressively; I was feeling frustrated when I
wrote that and did not think it through.

docker version:
Client:
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfcd85
 Built:             Mon May 29 15:50:06 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f9ee
  Built:            Mon May 29 15:50:06 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.1
  GitCommit:        1677a17964311325ed1c31e2c0a3589ce6d5c30d.m
 runc:
  Version:          1.1.7
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

docker info:
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 1
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries
splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1677a17964311325ed1c31e2c0a3589ce6d5c30d.m
 runc version:
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.3.5-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.54GiB
 Name: new-host-1.fios-router.home
 ID: 130e0cee-a133-4da1-84e1-a7ca65f46a19
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

I am curious about why /usr/bin/dockerd as invoked by systemctl start docker
would reject "--features". Arch Linux is usually very close to upstream.
You can view the PKGBUILD for docker here
<https://gitlab.archlinux.org/archlinux/packaging/packages/docker/-/blob/main/PKGBUILD>;
they're drawing from https://github.com/moby/moby on tag v24.0.2. I poked
around the code a little, but I don't know Go and was not able to find
where the command line arguments are parsed.

Sorry for my careless words,
Mark Peschel

**Comment by cpuguy83** [comment]
@mpeschel10 
I actually quickly responded half way into reading the email notification first thing in the morning then I saw the rest of it and I'm like "oh I'm an idiot, let me just delete my post". 🤣

Thanks for reporting back!

**Comment by ajmeese7** [comment]
Still experiencing issues with this when the experimental `containerd` image store is turned ou, it just gives errors like the following when the download fails now:

```shell
$ docker pull catthehacker/ubuntu:act-latest
ead2e35d8404: Already exists
0ae2e750d57c: Already exists
79baa542d5d7: Already exists
4ca545ee6d5d: Already exists
e3f2863485da: Already exists
44ba2882f8eb: Downloading [>                                                  ]  7.555kB/30.44MB
09635eb7e6af: Downloading [=>                                                 ]  6.291MB/173MB
8b7d29649b7b: Downloading [>                                                  ]       0B/39.45MB
3bf0ff2153a6: Downloading [>                                                  ]       0B/201.3MB
failed to copy: tls: received record with version 4361 when expecting version 303
```

**Comment by unclehowell** [comment]
Bad drills that this isn't sorted. Sort it!
