### ISSUE TITLE
Docker Demon is unable to start after VM reboot unexpectly 

### ISSUE THREAD

**Issue by vinodh2020** [docker/for-linux#1316]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Steps to reproduce the behavior

**Output of `docker version`:**

```
docker version
Client: Docker Engine - Community
Version: 19.03.11-ol
API version: 1.40
Go version: go1.16.2
Git commit: 9bb540d
Built: Fri Jul 23 01:33:55 2021
OS/Arch: linux/amd64
Experimental: false
error during connect: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.40/version": read unix @->/var/run/docker.sock: read: connection reset by peer
```

**Output of `docker info`:**

```
docker info
Client:
Debug Mode: false



Server:
ERROR: error during connect: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.40/info": read unix @->/var/run/docker.sock: read: connection reset by peer
errors pretty printing info
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

physical

**Comment by thaJeztah** [comment]
I'd recommend checking the daemon logs and system logs to see if there's more information there that indicates why it fails to start.

From the version output (`19.03.11-ol`), based on the `-ol` suffix, it looks like you're running a version of Docker that's built by Oracle, so if you're having issue, the first point of support would be Oracle / the Oracle package maintainers.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the [Docker community Slack channel](http://dockr.ly/slack)
- the Docker Support Forums - https://forums.docker.com
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)

I'm closing this issue because of the above, but feel free to continue the conversation
