### ISSUE TITLE
Docker json driver append time to the split original log (over 16K)

### ISSUE THREAD

**Issue by EvanLjp** [docker/for-linux#1321]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
when a single line stdout reach 16K, the single line would be split to few lines.
{"log":"{\"@timestamp\":\"2021-10-18T17:35:54.263Z\",xxxxxxx ","stream":"stdout","time":"2021-10-20T02:35:38.970719033Z"}
{"log":"the another parts","stream":"stdout","time":"2021-10-20T02:35:38.970719033Z"}

### Actual behavior

{"log":"{\"@timestamp\":\"2021-10-18T17:35:54.263Z\",xxxxxxx ","stream":"stdout","time":"2021-10-20T02:35:38.970719033Z"}
{"log":"2021-10-18T17:35:54.266092638+08:00 the another parts","stream":"stdout","time":"2021-10-20T02:35:38.970719033Z"}

the following images show the cases, and I found the position of the time is not fixed. 

![image](https://user-images.githubusercontent.com/31562192/138819445-7cf00b38-6b03-4a94-aeba-4ce06907b80c.png)
![image](https://user-images.githubusercontent.com/31562192/138819483-4784991d-fff1-45f3-af8b-ea6837116b66.png)

### Steps to reproduce the behavior
1. prepare a big single line file, and print it to the stdout
2. use json log driver
3. read the docker json log

**Output of `docker version`:**

```
$docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.40
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:49 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9d988398e7
  Built:            Fri May 15 00:24:05 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 50
  Running: 0
  Paused: 0
  Stopped: 50
 Images: 119
 Server Version: 19.03.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.91-011.ali4000.alios7.x86_64
 Operating System: Alibaba Group Enterprise Linux Server 7.2 (Paladin)
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 60.64GiB
 Name: sls-backend-server-test011122076082.na131
 ID: FI6P:EDLW:RY36:HDCI:MFYX:KHJV:TFXJ:X5JF:WR6X:FVAW:ZAYD:N7PT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Alibaba ECS

**Comment by thaJeztah** [comment]
First of all, note that the `xx-json.log` files that are stored by the JSON-file logging driver are intended as an internal storage only, and meant to be used using the `docker container logs` / `docker logs` commands, not to be meant for external use.

I read your description, but not sure what the exact issue is that you're running into; could you explain the problem a bit more?


The logging system used in Docker is based on line-delimited output in the container's stdout/stderr, and (as you mentioned) limited to 16k per entry. Output longer than that, which does not have a newline will be split, but are still considered to be part of the same log message, and thus have the same timestamp.

For example; this starts a container that

1. prints a 17k string of "a"'s (without newlines)
2. then a 1 second sleep (to mimic the log output taking some time), followed by "done" (and a newline)
3. waits another second, and then prints a "next log line"

In the above, `1.` and `2.` are both part of the same log entry (as there's only a single newline after `done`), but (because it's more than 16k) the log-entry is split to two partial messages in the `xx-json.log` file on disk. `3.` is a new log message.

```
$ docker run -d --name mycontainer ubuntu bash -c 'printf '"'"'a%.0s'"'"' {1..17000} && sleep 1 && echo "done" && sleep 1 && echo "next log line"'
197720a61da966717e7f8dabba8712133471031169418aededaabd972e3d6b7a
```

Looking at the log file on disk, you can see that the first two entries have the same timestamp, as they're both "partial" messages, part of the first log message. The last entry is for the "next log line", and has a different timestamp;

```bash
$ cat /var/lib/docker/containers/197720a61da966717e7f8dabba8712133471031169418aededaabd972e3d6b7a/197720a61da966717e7f8dabba8712133471031169418aededaabd972e3d6b7a-json.log | jq .time
"2022-01-04T10:55:23.662130838Z"
"2022-01-04T10:55:23.662130838Z"
"2022-01-04T10:55:25.671032961Z"
```

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
