### ISSUE TITLE
No rpms available at https://download.docker.com/linux/rhel/

### ISSUE THREAD

**Issue by jby** [docker/for-linux#1322]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
Ability to install rpms using the provided rpm-repo, as described in the official documentation:
https://docs.docker.com/engine/install/rhel/#install-using-the-repository

### Actual behavior
Nothing is installed since the repo seems to be empty...

### Steps to reproduce the behavior
* Add repo according to documentation
* Ty to install according to documentation

**Additional environment details (AWS, VirtualBox, physical, etc.)**

RHEL 7.9

**Comment by thaJeztah** [comment]
I suspect you're trying to install on (e.g.) an x86 machine. Packages for RHEL are provided in partnership with IBM, and currently only provided for s390x, see the support matrix at https://docs.docker.com/engine/install/#server, and the "prerequisites" section at https://docs.docker.com/engine/install/rhel/#prerequisites. While we currently don't provide RHEL packages for other architectures, you may be able to install the CentOS packages, or open a feature request in the public roadmap (which helps prioritizing such requests); https://github.com/docker/roadmap


I'm closing this ticket because of the above, but feel free to continue the conversation

**Comment by jby** [comment]
Yeah, the CentOS rpms did work fine.
