### ISSUE TITLE
Multi-stage cache bringing back deleted files

### ISSUE THREAD

**Issue by kichik** [docker/for-linux#135]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

I have a simple Dockerfile with two stages. First I copy some files, run a small build script and then delete the original files. My second stage copies the result from the first stage. I would expect the deleted files to not be there, but sometimes they show up unless I use `--no-cache` when building.

### Actual behavior

Deleted files are somehow left in the container.

### Steps to reproduce the behavior

To reproduce create an empty folder with this `Dockerfile`:
```
FROM python:3.6 AS compiled

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app

RUN python -m compileall -b .
RUN find . -name "*.py" -type f | xargs rm -fv

# actual image
FROM python:3.6

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY --from=compiled /usr/src/app .

ENTRYPOINT ls
```

Then run this command:

```
touch a.py && rm -f b.py && docker build --no-cache -t test . && docker run --rm test && cp a.py b.py && docker build -t test . && docker run --rm test
```

You'll see the first time the container runs (middle of the output), you only get `a.pyc` as the result of `ls`. But the second time it runs, the removed `.py` files come back to life.

```
[....]
removed ‘./a.py’
[....]
Dockerfile
a.pyc
[....]
 ---> Using cache
[....]
 ---> Running in 0178c7c81be0
removed ‘./b.py’
removed ‘./a.py’
[....]
Dockerfile
a.py
a.pyc
b.py
b.pyc
```

My current workaround for this is to always disable the cache, but my builds become much slower. I've also noticed, as the example shows, that the input of the first stage must be different for this to happen (it doesn't happen without `cp a.py b.py`).

**Output of `docker version`:**

```
Docker version 17.09.0-ce, build afdb6d4
```

**Output of `docker info`:**

```
Containers: 74
 Running: 0
 Paused: 0
 Stopped: 74
Images: 487
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 502
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-37-generic
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990MiB
Name: ubuntu
ID: TAF3:JIHX:L4NV:KJ5A:AYPX:J4IU:LB66:KGJP:ZUAK:UVEQ:TLAJ:OKFE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

I'm running on a fully up-to-date Ubuntu 17.04 running inside VirtualBox 5.1.30.

**Comment by kichik** [comment]
The two `RUN` lines can also be replaced with the following simpler lines to get the same output.

```
RUN cp a.py a.pyc && cp b.py b.pyc || echo no b yet
RUN rm -f *.py
```

The issue only occurs when `b.pyc` is created in the first stage of the second build. If the second `cp` in the above `RUN` line is removed, it behaves as expected.

**Comment by thaJeztah** [comment]
Do you see the same happening if you use the overlay2 storage driver instead of aufs?

**Comment by kichik** [comment]
It happens with `overlay2` as well.

```
user@ubuntu:~/docker-bug$ touch a.py && rm -f b.py && docker build --no-cache -t test . && docker run --rm test && cp a.py b.py && docker build -t test . && docker run --rm test
[...]
a.py
a.pyc
b.py
b.pyc
```
```
user@ubuntu:~/docker-bug$ docker info | grep Storage
WARNING: No swap limit support
Storage Driver: overlay2
```

**Comment by kichik** [comment]
It happens with the old `overlay` too.

**Comment by kichik** [comment]
This also happens on Ubuntu 17.10 running on AWS (`ami-8fd01af5`).

**Comment by tonistiigi** [comment]
@dnephin I think I finally figured out what's going on here. It's basically the topic we've discussed many times in the past that `releasableLayer.Mount` isn't really a mount call but a combination of new and mount that mixes with the `Commit` logic. In the more correct API there would be a `layer.New()` that creates a layer that can be committed.

In here there are 2 stages that share the first commands (up to `WORKDIR`). On the second run the `WORKDIR` in the second stage would match the cache for the `WORKDIR` in the first stage. The next copy reuses the mount for the destination target because it was also used in the `COPY` in first stage. But as the mount does not actually just mount but creates an internal rwlayer the second call will just return back the same rwlayer that was used in the first stage. So atm `Mount()` is cached and creates rw internally, commit is per operation. It should be that `mount()` is cached, new and commit are per operation.

Let me know if you have some ideas for fixing this with minimal effort without having a big update to the interface (as none of these issues exists in buildkit).

**Comment by tonistiigi** [comment]
@kichik There is an easy workaround. Just add any command before the second `COPY`, like `WORKDIR .`. The issue is that if you have 2 stages that have identical commands up to the `COPY` instruction the files that were copied in the first stage are already in the destination path for the second stage before the second copy even begins. By making the previous commands slightly different the issue won't appear.

**Comment by kichik** [comment]
The workaround solved it for me. Thanks!

**Comment by dnephin** [comment]
I don't have any idea for an easy fix. I think we need to fix the interface as you've described.

**Comment by AkihiroSuda** [comment]
@tonistiigi @dnephin 

The issue seems critical, and it can even potentially cause security issues.

If we can't fix the issue until we integrate BuildKit, can we detect problematic Dockerfile and print warning message on the console?

Also, we may internally insert NOP into such Dockerfile, but it may cause another problem.
