### ISSUE TITLE
API `Mount` type mismatch Target vs Destination

### ISSUE THREAD

**Issue by thechubbypanda** [docker/for-linux#1361]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
API v1.41 Endpoint `/containers/json` returns 
```
0:
  Mounts:
    0:
      Target: "/data"
```

### Actual behavior
API v1.41 Endpoint `/containers/json` returns 
```
0:
  Mounts:
    0:
      Destination: "/data"
```

Expected according to docs [here](https://docs.docker.com/engine/api/v1.41/#operation/ContainerList):

![image](https://user-images.githubusercontent.com/33595996/155885404-7b126973-4a18-4b6e-8a88-04cd94f1286f.png)

### Steps to reproduce the behavior

1. Start `dockerd` with default socket and unauthenticated http api on port 5000 (`/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:5000`)
2. `docker run --rm portainer/portainer-ce` (Or any container with a volume)
3. http://localhost:5000/containers/json
4. Observe the incorrect value name in the /data mount

**Output of `docker version`:**

```
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.17.5
 Git commit:        e91ed5707e
 Built:             Mon Dec 13 22:31:40 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.5
  Git commit:       459d0dfbbb
  Built:            Mon Dec 13 22:30:43 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.0
  GitCommit:        39259a8f35919a0d02c9ecc2871ddd6ccf6a7c6e.m
 runc:
  Version:          1.1.0
  GitCommit:        v1.1.0-0-g067aaf85
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  compose: Docker Compose (Docker Inc., 2.2.3)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 39259a8f35919a0d02c9ecc2871ddd6ccf6a7c6e.m
 runc version: v1.1.0-0-g067aaf85
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.16.11-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.1GiB
 Name: REDACTED
 ID: GYCD:EW5G:MXR3:J535:2NGN:SPT3:HPF2:VPUS:IINE:4XBM:WWDQ:ZZHV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment]
Thanks for reporting; this was a mistake in the swagger file used to generate the API docs, which accidentally picked the [`Mount` definition](https://github.com/moby/moby/blob/v20.10.15/docs/api/v1.41.yaml#L336-L344) instead of the [`MountPoint` definition](https://github.com/moby/moby/blob/v20.10.15/docs/api/v1.41.yaml#L203-L245).

This was resolved in https://github.com/moby/moby/pull/42129 and back ported to the 20.10 release branch (which is used for the documentation) in https://github.com/moby/moby/pull/43460

documentation now looks to be correct; https://docs.docker.com/engine/api/v1.41/#operation/ContainerInspect

<img width="836" alt="Screenshot 2022-05-06 at 11 31 36" src="https://user-images.githubusercontent.com/1804568/167106128-719e5917-e57f-4b5c-9604-dc704ac6b8a4.png">


Let me close this one; thanks again for reporting, and feel free to continue the conversation
