### ISSUE TITLE
Swarm Mode 17.10-ce: Cannot allocate memory

### ISSUE THREAD

**Issue by lukeescude** [docker/for-linux#137]
We have Docker running in Swarm Mode across 6 hosts - All of them are Managers. There are 0 worker nodes.

We have about 50 containers running across all 6 nodes, nothing crazy, but recently we've been having a manager node lock up, and stop running completely.

There are two errors that pop up a lot during one of these lock-ups:
failed to retrieve docker-runc version: fork/exec /usr/bin/docker-runc: cannot allocate memory
failed to retrieve docker-init version: fork/exec /usr/bin/docker-init: cannot allocate memory

During the lock-up, the containers just freeze. They don't reschedule on another manager node, they just sit there and cease operation.

How should we go about diagnosing this issue?

Note: Each Manager has 16GB ram, but the containers only occupy about 3 of that or less. When this event occurs, the host is reporting no abnormal RAM usage.

Also note that the issue resolves itself if we DRAIN the node, then put it back live again. We don't need to restart the host or anything. Simply draining will "fix" it til it crashes next time.

**Comment by thaJeztah** [comment]
Can you provide the output of `docker version`, and  `docker info`? Anything interesting in the logs for the docker service, or system logs?

**Comment by thaJeztah** [comment]
Note that adding more managers only accounts for improving availability, but will definitely have a negative effect on performance; more managers will result in a higher overhead due to leader (re)election and managing the raft store; using an even number of managers is not recommended. For a small cluster, 1 manager, or 3 managers (for fault tolerance) is more common.

Putting load on manager nodes increases the risk that the manager does not have sufficient resources to perform its tasks, which can result in losing control over the cluster. See https://docs.docker.com/engine/swarm/admin_guide/, and https://docs.docker.com/engine/swarm/raft/ for more information on this,

**Comment by thaJeztah** [comment]
There's more information in the ossis opened in https://github.com/moby/moby/issues/35243#issuecomment-340580998, let me close this issue for the same reason, but feel free to comment after I closed
