### ISSUE TITLE
Failed to start docker: Failed to start LSB: Create lightweight, portable, self-sufficient containers..

### ISSUE THREAD

**Issue by vikash291** [docker/for-linux#1413]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Actual behavior
docker suddenly stops running. there are few container which are running on the docker.

### Steps to reproduce the behavior
i tried to run the build using docker-compose build. 

```sudo systemctl start docker.service```

**Output of `docker version`:**

```
Docker version 20.10.6, build 370c289
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
its a aws  ec2 Ubuntu instance.

when i tried to start the server getting this error:

```
● docker.service - LSB: Create lightweight, portable, self-sufficient containers.
   Loaded: loaded (/etc/init.d/docker; generated)
   Active: failed (Result: exit-code) since Thu 2022-06-30 11:10:58 UTC; 1min 13s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 2927 ExecStart=/etc/init.d/docker start (code=exited, status=1/FAILURE)

Jun 30 11:10:58 ip-172-31-25-79 systemd[1]: Starting LSB: Create lightweight, portable, self-sufficient containers....
Jun 30 11:10:58 ip-172-31-25-79 docker[2927]:  * /usr/bin/dockerd not present or not executable
Jun 30 11:10:58 ip-172-31-25-79 systemd[1]: docker.service: Control process exited, code=exited status=1
Jun 30 11:10:58 ip-172-31-25-79 systemd[1]: docker.service: Failed with result 'exit-code'.
Jun 30 11:10:58 ip-172-31-25-79 systemd[1]: Failed to start LSB: Create lightweight, portable, self-sufficient containers..
```

**Comment by thaJeztah** [comment]
Was this a fresh install, or an existing setup? What distro are you running on and how did you install? The error message indicates that something 's wrong with the binary?

```
 /usr/bin/dockerd not present or not executable
```


The version of docker also looks to be quite old (current patch release of docker is 20.10.17).


Based on the information in this ticket, I don't think there's a bug at hand, but something broken in your installation; I'd recommend (if possible) to re-install docker using the instructions at https://docs.docker.com/engine/install/ubuntu/

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the [Docker community Slack channel](http://dockr.ly/slack)
- the Docker Support Forums - https://forums.docker.com
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)

I'm closing this issue because of the above, but feel free to continue the conversation 👍
