### ISSUE TITLE
Docker not respecting host interface MTU

### ISSUE THREAD

**Issue by wjeffs-edb** [docker/for-linux#1426]
When running VMs on VXLANs ect, its common for VMs to drop the MTU under 1500 to 1450 or less.

Docker by default does not respect this and tries to bring up containers with a MTU of 500, which then causes issues with connectivity.

We have been getting around this by having to set the MTU manually in "/etc/docker/daemon.json" but I feel this is something docker should handle out the box.

I have tested this on Ubuntu and Centos 8.

**Comment by thaJeztah** [comment]
If I'm not mistaken, this was changed on purpose; see https://github.com/moby/moby/pull/18108 (and the related ticket https://github.com/moby/moby/issues/7796); before that change, the daemon would attempt to detect the correct MTU to use, but there were many situations where that would fail, or set the wrong value; because of that it was decided to require the user to set the correct value.

Slightly related; there's a PR being reviewed to add some configuration option for this; https://github.com/moby/moby/pull/43197

**Comment by thaJeztah** [comment]
Looks like this went stale; and there's nothing actionable in this ticket, so let me go ahead and close it.
