### ISSUE TITLE
Docker won't start on raspberry pi

### ISSUE THREAD

**Issue by Tombost** [docker/for-linux#149]
Hello,
I use docker for one mounth without problem, but today I start my raspberry pi and my dotnet and mqtt container will not run.
Run : docker run -d -p 1883:1883 -p 9001:9001 ericmick/armhf-mosquitto:latest

Result : Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

So i test : sudo systemctl start docker.service but the result is : 
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

status of docker.service is : 

`● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-10-30 14:41:58 CET; 19s ago
     Docs: https://docs.docker.com
  Process: 4032 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=2)
 Main PID: 4032 (code=exited, status=2)
      CPU: 1.838s

oct. 30 14:41:59 raspberrypi dockerd[4032]: r8      0x4676a9ac
oct. 30 14:41:59 raspberrypi dockerd[4032]: r9      0x1000
oct. 30 14:41:59 raspberrypi dockerd[4032]: r10     0x569cc5a0
oct. 30 14:41:59 raspberrypi dockerd[4032]: fp      0x1c21330
oct. 30 14:41:59 raspberrypi dockerd[4032]: ip      0x20
oct. 30 14:41:59 raspberrypi dockerd[4032]: sp      0x4676a898
oct. 30 14:41:59 raspberrypi dockerd[4032]: lr      0xffffffff
oct. 30 14:41:59 raspberrypi dockerd[4032]: pc      0x76cda45c
oct. 30 14:41:59 raspberrypi dockerd[4032]: cpsr    0x10
oct. 30 14:41:59 raspberrypi dockerd[4032]: fault   0x0`

My full journalctl about docker is : 
[https://pastebin.com/cC3sMNfa](url)

Docker version : 
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

What I need to do ? I can't backup my images i really need it and then maybe reinstall docker or find a solution ...

thanks

**Comment by cpuguy83** [comment]
> oct. 30 14:22:12 raspberrypi dockerd[3670]: runtime/cgo: pthread_create failed: Resource temporarily unavailable

Is there a `TaskMax` set in the docker systemd unit file?
Is your process table full?

**Comment by Tombosy** [comment]
Hi,
In my : /lib/systemd/system/docker.service section service I have : 

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd -H fd://
ExecReload=/bin/kill -s HUP $MAINPID
LimitNOFILE=1048576
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
#TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process
# restart the docker process if it exits prematurely
Restart=on-failure
StartLimitBurst=3
StartLimitInterval=60s

So no taskmask settings

What do you meen by process table full ?
Ram only use 200Mo
Not other process, juste two docker : dotnet core and mqtt

**Comment by cpuguy83** [comment]
> What do you meen by process table full ?

If number of tasks == `/proc/sys/kernel/threads-max` then you won't be able to create new threads.
If you don't have enough ram you would also not be able to create more threads.

**Comment by Tombost** [comment]
I'm not sure about number of tasks, but htop say 312 thr
My value of `/proc/sys/kernel/threads-max` is 14693

**Comment by cpuguy83** [comment]
Closing because this is not a Docker issue but rather due to limited resources on the host machine preventing the go runtime from creating new threads.

All I can really do here is give you some pointers. 

> Resource temporarily unavailable

This is the error that is thrown. It means that a resource on the host is exhausted.
It could be that there are too many tasks on the system (this is a combination of threads and processes).
It could be that there is not enough memory available to create a new thread... You could try enabling swap and see if that helps.
Potentially something else?

**Comment by aefo** [comment]
Looks like https://github.com/docker/for-linux/issues/783#issuecomment-575637222 helped resolve similar issue by deleting the container data.
