### ISSUE TITLE
DNS resolution starts failing inside the docker container only

### ISSUE THREAD

**Issue by mattlegall** [docker/for-linux#1509]
During initial deployment of the docker container, DNS resolution works on the host and inside the docker container. **After some time, for a reason that we don't understand, DNS resolution starts failing inside the docker container while it is properly working on the host.** /etc/resolv.conf is matching on host and container.

Example:
[user@source ~ ]$ nslookup <destination_fqdn>
Server:         172.x.x.x
Address:        172.x.x.#53
Name:   <destination_fqdn>
Address: 10.x.x.x
[user@source ~ ]$ docker exec -it <instance> /bin/sh
/ $ nslookup <destination_fqdn>
**;; connection timed out; no servers could be reached**

We are not able to replicate the issue as we don't know the root cause. We are restarting the docker container as a workaround and the issue gets fixed.

We have seen this against docker version below:
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:46:45 2023
 OS/Arch:           linux/amd64
 Context:           default
Server: Docker Engine - Community
 Engine:
  Version:          23.0.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       d7573ab
  Built:            Wed Feb  1 17:44:25 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by mattlegall** [comment]
Any hints on this one?
Or a related/similar issue?

**Comment by akerouanton** [comment]
Hi @mattlegall, this is a legacy issue tracker we don't regularly watch. New issues should be reported on https://github.com/moby/moby.

I see that you're using Docker Engine v23.0. Note that this version is deprecated, and the bug you're experiencing might well be caused by something that has been fixed since this version's release.

You don't mention how you created your container but since you've `Address: 172.x.x.x` in your nslookup output, I assume you're running this container on the default bridge (ie. you didn't specify a custom `--network`). Is that right?

This IP address is looking a bit suspicious as it looks like an IP address for a Docker network. Did you check that there's no conflict between custom networks and that address?

**Comment by mattlegall** [comment]
Thanks for the feedback. I will close the issue here and re-create on moby side.

Regarding the IP address, I double checked and there is nothing conflicting at 172.x.x.x between host and container
