### ISSUE TITLE
Proposal: shutdown Fedora repos

### ISSUE THREAD

**Issue by lig** [docker/for-linux#181]
I'd like to propose to shutdown docker-ce Fedora repos support.
They are empty or simply do not exist most of the time for the latest release. Thus it is mostly useless exercise to support this.

See related issues:
https://github.com/docker/for-linux/issues/164
https://github.com/docker/for-linux/issues/143
https://github.com/docker/for-linux/issues/35

**Comment by thaJeztah** [comment]
You don't have to use them if you don't want to; others may still do

**Comment by lig** [comment]
@thaJeztah the problem is I cannot. And nobody can, who have recent enough Fedora. So, there is no good Fedora support for Docker CE releases. Why keep doing something if it is not good? It is better to give up and accept that you cannot handle it. In such a case the community will step in as people will be aware of you don't support Fedora. In the current situation, you are making false claims about having Fedora supported.

**Comment by thaJeztah** [comment]
As explained in other issues; the installation manual states exactly which version of each distro is supported. Given that there's a monthly release cycle, there may be up to a month delay between a Fedora release and a Docker release for that version.

So, to run Docker;

- Make sure your system matches the requirements (which may be "last month's" version of Fedora, which is still supported by the Fedora community)
- Install Docker.

**Comment by lig** [comment]
F27 release date is 2017-11-14.

What does "last month's" exactly mean?

Does it mean that on the day after tomorrow (Dec'14) the F27 repo will be populated with the Docker release? Or does it mean that in Dec I should be able to use F27 which was released last month?

This simply doesn't make sense for me. We've waited for the repo to be available for F26 a lot longer than a month.

And what if something goes wrong? Maybe it is worth to have time to test Docker on the upcoming distro version before it goes GA? I still think that this release policy you insist on is a complete nonsense that is out of use for anybody doing continues upgrades and integration. At least edge (test series too, probably) should have a version of Docker for upcoming Fedora release present in the repo way before the actual release. Otherwise, please, consider dropping Fedora support completely to pass the community a clear and honest signal that you cannot handle it.

**Comment by seitzbg** [comment]
I wanted to try Docker out on my F27-Server host and found this thread. No soup for me eh?

**Comment by seemethere** [comment]
You can install docker right now on Fedora 27 without issue using get.docker.com

Users have reported no issues with the old Fedora 26 packages working with Fedora 27. 

If you'd like to install Docker, right now, on Fedora 27 all you would need to do is

```
curl -fsSL get.docker.com | sh
```

**Comment by lig** [comment]
@seemethere LOL
```
[root@5cff30d6ec16 /]# curl -fsSL get.docker.com | sh
# Executing docker install script, commit: 11aa13e
+ sh -c 'dnf install -y -q dnf-plugins-core'
+ sh -c 'dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo'
Adding repo from: https://download.docker.com/linux/fedora/docker-ce.repo
+ '[' 27 -eq 27 ']'
+ sh -c 'sed -i '\''s/\$releasever/26/g'\'' /etc/yum.repos.d/docker-ce.repo'
+ set +x
==================================================================================

WARNING: Hardcoding repository to use Fedora 26 repositories
         You will need to update your repositories after the release of 17.12.0-ce

         See: https://github.com/docker/for-linux/issues/164#issuecomment-345034887

==================================================================================
+ '[' edge '!=' stable ']'
+ sh -c 'dnf config-manager --set-enabled docker-ce-edge'
```

**Comment by schuerg** [comment]
Today we have the 21.12.2017 and the Fedora 27 repository is still empty.

> The Fedora Project releases a new version of Fedora approximately every 6 months

I understand it's difficult to follow this fast cycle, but waiting for the Docker Repo every 6 months for 1-2 months is not appropriate.

Then maybe it's better not to claim to support it officially because people rely on availability.

**Comment by thaJeztah** [comment]
> Today it is 2017-12-21 and the Fedora 27 repository is still empty.

Correct, 17.12 has not been released; you can find release-candidates in the "test" channel

17.12 is intended to be released in December (which it still is); release dates sometimes shift (which is not uncommon for other software as well);

<img width="1077" alt="screen shot 2017-12-21 at 12 21 06" src="https://user-images.githubusercontent.com/1804568/34253837-8974391e-e649-11e7-874c-c9fa183c0b71.png">


Anyway; as mentioned earlier https://github.com/docker/for-linux/issues/181#issuecomment-350919968, the documentation states which versions of each distro are supported. No support is "claimed" for Fedora 27 yet.


I'm locking the conversation on this issue, because all relevant information can be found in this thread already, and continuing this conversation is only wasting time better spent on other things.

**Comment by seemethere** [comment]
For those coming to this comment at a later date, `17.12.0-ce` has officially been released and packages for Fedora 27 are officially now available.
