### ISSUE TITLE
<root-device> mounted to /var/lib/docker/plugins

### ISSUE THREAD

**Issue by kapad** [docker/for-linux#260]
Why is my systems root device (`/dev/mapper/system-root` in my case) mounted to `/var/lib/docker/plugins`?

Be default this device is already mounted to `/`. After I installed docker, I noticed that now this same device is also mounted to `/var/lib/docker/plugins`

**Comment by cpuguy83** [comment]
Because "/var/lib/docker/plugins" is bind-mounted to itself so it can remount the dir with "private" propagation to protect certain plugin mounts.

The device itself is not mounted there.

Note that in a future version this no longer happens as we now protect the mounts by performing them in the runtime instead of on the host.

Closing since this is a non-issue, but feel free to discuss.
