### ISSUE TITLE
Can't start docker on ubuntu (16.04)

### ISSUE THREAD

**Issue by EFugier** [docker/for-linux#281]
* I am running Ubuntu 16.04 LTS (up to date)

* Re-installing docker does not fix the problem

Here is the list of commands / errors (happening after a fresh install, I have no containers)

# 1

    > sudo dockerd
    Error starting daemon: pid file found, ensure docker is not running or delete /var/run/docker.pid

# 2

    > sudo rm /var/run/docker.pid
    > sudo dockerd
    INFO[2018-04-15T15:36:53.366173518+02:00] libcontainerd: docker-containerd is still running  pid=1639
    [waits for 5 seconds]
    Failed to connect to containerd: failed to dial "/var/run/docker/containerd/docker-containerd.sock": dial unix:///var/run/docker/containerd/docker-containerd.sock: timeout

# 3

    > sudo kill 1639
    > sudo dockerd
    INFO[2018-04-15T15:40:16.902201524+02:00] libcontainerd: started new docker-containerd process  pid=4458
    [lots of probably useless stuff...]
    INFO[2018-04-15T15:40:16.926740324+02:00] [graphdriver] using prior storage driver: overlay2 
    Error starting daemon: error while opening volume store metadata database: timeout

and from here we are back to **2**...

If I restart the computer I go back to **1**.

**Comment by EFugier** [comment]
Well apparently, once installed docker will always start on boot... so the error came from the fact that docker was already running... I won't detail here the bug chain that let me assume it was not. I am sorry.

**Comment by efugier** [comment]
As far as I remeber, I gave up and used a friend's computer as I only had a small thing to do. Sorry...

**Comment by thanos1983** [comment]
I know this is an old question but just in case that someone might have the same problem here is what worked for me.

Step 1:
(sudo) systemctl status docker

If the docker is running you will get something like:

$ systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; disabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-04-08 11:34:39 CEST; 33s ago
     Docs: https://docs.docker.com
 Main PID: 13714 (dockerd)
    Tasks: 18
   Memory: 34.2M
   CGroup: /system.slice/docker.service
           └─13714 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.397942657+02:00" level=warning msg="Your kernel does not support swap memory limit"
Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.397986822+02:00" level=warning msg="Your kernel does not support cgroup rt period"
Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.397998384+02:00" level=warning msg="Your kernel does not support cgroup rt runtime"
Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.398401944+02:00" level=info msg="Loading containers: start."
Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.662918633+02:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to 
Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.783450081+02:00" level=info msg="Loading containers: done."
Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.882945376+02:00" level=info msg="Docker daemon" commit=d14af54 graphdriver(s)=overlay2 version=18.09.4
Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.883023443+02:00" level=info msg="Daemon has completed initialization"
Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.907022845+02:00" level=info msg="API listen on /var/run/docker.sock"
Apr 08 11:34:39 tinyos systemd[1]: Started Docker Application Container Engine.

Step 2:
(sudo) systemctl stop docker

$ systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; disabled; vendor preset: enabled)
   Active: inactive (dead) since Mon 2019-04-08 11:35:30 CEST; 1s ago
     Docs: https://docs.docker.com
  Process: 13714 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=0/SUCCESS)
 Main PID: 13714 (code=exited, status=0/SUCCESS)

Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.783450081+02:00" level=info msg="Loading containers: done."
Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.882945376+02:00" level=info msg="Docker daemon" commit=d14af54 graphdriver(s)=overlay2 version=18.09.4
Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.883023443+02:00" level=info msg="Daemon has completed initialization"
Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.907022845+02:00" level=info msg="API listen on /var/run/docker.sock"
Apr 08 11:34:39 tinyos systemd[1]: Started Docker Application Container Engine.
Apr 08 11:35:30 tinyos systemd[1]: Stopping Docker Application Container Engine...
Apr 08 11:35:30 tinyos dockerd[13714]: time="2019-04-08T11:35:30.224574738+02:00" level=info msg="Processing signal 'terminated'"
Apr 08 11:35:30 tinyos dockerd[13714]: time="2019-04-08T11:35:30.226299525+02:00" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
Apr 08 11:35:30 tinyos dockerd[13714]: time="2019-04-08T11:35:30.227150601+02:00" level=error msg="remove /var/run/docker.pid: no such file or directory"
Apr 08 11:35:30 tinyos systemd[1]: Stopped Docker Application Container Engine.

Step 3:
$ sudo dockerd
INFO[2019-04-08T11:35:44.909055379+02:00] systemd-resolved is running, so using resolvconf: /run/systemd/resolve/resolv.conf 
INFO[2019-04-08T11:35:44.909604039+02:00] parsed scheme: "unix"                         module=grpc
INFO[2019-04-08T11:35:44.909617448+02:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-04-08T11:35:44.909647733+02:00] parsed scheme: "unix"                         module=grpc
INFO[2019-04-08T11:35:44.909657202+02:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-04-08T11:35:44.909713390+02:00] ccResolverWrapper: sending new addresses to cc: [{unix:///run/containerd/containerd.sock 0  <nil>}]  module=grpc
INFO[2019-04-08T11:35:44.909739132+02:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-04-08T11:35:44.910142846+02:00] pickfirstBalancer: HandleSubConnStateChange: 0xc42017abe0, CONNECTING  module=grpc
INFO[2019-04-08T11:35:44.909722086+02:00] ccResolverWrapper: sending new addresses to cc: [{unix:///run/containerd/containerd.sock 0  <nil>}]  module=grpc
INFO[2019-04-08T11:35:44.910200925+02:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-04-08T11:35:44.910504660+02:00] pickfirstBalancer: HandleSubConnStateChange: 0xc42017ad10, CONNECTING  module=grpc
INFO[2019-04-08T11:35:44.910764106+02:00] pickfirstBalancer: HandleSubConnStateChange: 0xc42017abe0, READY  module=grpc
INFO[2019-04-08T11:35:44.911108343+02:00] pickfirstBalancer: HandleSubConnStateChange: 0xc42017ad10, READY  module=grpc
INFO[2019-04-08T11:35:44.910236232+02:00] blockingPicker: the picked transport is not ready, loop back to repick  module=grpc
INFO[2019-04-08T11:35:44.912084762+02:00] [graphdriver] using prior storage driver: overlay2 
INFO[2019-04-08T11:35:44.927898040+02:00] Graph migration to content-addressability took 0.00 seconds 
WARN[2019-04-08T11:35:44.928256050+02:00] Your kernel does not support swap memory limit 
WARN[2019-04-08T11:35:44.928307843+02:00] Your kernel does not support cgroup rt period 
WARN[2019-04-08T11:35:44.928323493+02:00] Your kernel does not support cgroup rt runtime 
INFO[2019-04-08T11:35:44.928811351+02:00] Loading containers: start.                   
INFO[2019-04-08T11:35:45.207943761+02:00] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
INFO[2019-04-08T11:35:45.319436873+02:00] Loading containers: done.                    
INFO[2019-04-08T11:35:45.439639218+02:00] Docker daemon                                 commit=d14af54 graphdriver(s)=overlay2 version=18.09.4
INFO[2019-04-08T11:35:45.439733271+02:00] Daemon has completed initialization          
INFO[2019-04-08T11:35:45.464199779+02:00] API listen on /var/run/docker.sock

Hope this helps someone else.

**Comment by mohanmaniramesh** [comment]
Thank u it helped Me..

**Comment by Lissen01** [comment]
Muchas gracias funciono.

**Comment by yonatansc97** [comment]
Thank you very much, it worked right away :) 👍

**Comment by galin-s** [comment]
thanos1983, thanks a lot, man!

**Comment by Djamac** [comment]
Thank you very much

**Comment by paulcasta** [comment]
so i been waiting for a while after using "sudo dockerd" do i have to do something else? @thanos1983

**Comment by thanos1983** [comment]
> so i been waiting for a while after using "sudo dockerd" do i have to do something else? @thanos1983

Hello @paulcasta ,

Is the daemon running after?

Check the status:

```bash
systemctl status docker
```
Is it running? If not try to restart it after:

```bash
sudo systemctl restart docker
```

See if it is working after.

Hope this helps.

BR / Thanos

**Comment by wasimdf** [comment]
Hi....
For me  it shows as below
-- Welcome to 4Minitz in Docker--*
*                                 *
* IF                              *
*   you launched the container    *
*   with the -p 3100:3333 option  *
* THEN                            *
*   You can open 4Minitz on your  *
*   host browser via:             *
*   http://localhost:3100

in 4minitz_settings.json i have even changed the root_url values also but still not able to access from browser...
can anyone suggest me what to be done

**Comment by wasimdf** [comment]
Can anyone help me to access the link from outside server ?
Like what all changes we have to do to access from any location and browser....

**Comment by thanos1983** [comment]
> Can anyone help me to access the link from outside server ?
> 
> Like what all changes we have to do to access from any location and browser....

Hello @wasimdf,

This kind of questions are better asked on relevant forums not on git hub where people report bugs.

I am not sure what are your configurations but from what you describe you need to enable the ipv4/6 forwarder.

Search on the web how to do that based on your version of Linux.

For example for Debian :

https://linuxhint.com/enable_ip_forwarding_ipv4_debian_linux/

Hope this helps.

BR / Thanos

**Comment by pavondunbar** [comment]
> I know this is an old question but just in case that someone might have the same problem here is what worked for me.
> 
> Step 1:
> `systemctl status docker`
> 
> If the docker is running you will get something like:
> 
> ```
> ● docker.service - Docker Application Container Engine
>    Loaded: loaded (/lib/systemd/system/docker.service; disabled; vendor preset: enabled)
>    Active: active (running) since Mon 2019-04-08 11:34:39 CEST; 33s ago
>      Docs: https://docs.docker.com
>  Main PID: 13714 (dockerd)
>     Tasks: 18
>    Memory: 34.2M
>    CGroup: /system.slice/docker.service
>            └─13714 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
> 
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.397942657+02:00" level=warning msg="Your kernel does not support swap memory limit"
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.397986822+02:00" level=warning msg="Your kernel does not support cgroup rt period"
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.397998384+02:00" level=warning msg="Your kernel does not support cgroup rt runtime"
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.398401944+02:00" level=info msg="Loading containers: start."
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.662918633+02:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to 
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.783450081+02:00" level=info msg="Loading containers: done."
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.882945376+02:00" level=info msg="Docker daemon" commit=d14af54 graphdriver(s)=overlay2 version=18.09.4
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.883023443+02:00" level=info msg="Daemon has completed initialization"
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.907022845+02:00" level=info msg="API listen on /var/run/docker.sock"
> Apr 08 11:34:39 tinyos systemd[1]: Started Docker Application Container Engine.
> ```
> 
> Step 2:
> `systemctl stop docker`
> 
> ```
> ● docker.service - Docker Application Container Engine
>    Loaded: loaded (/lib/systemd/system/docker.service; disabled; vendor preset: enabled)
>    Active: inactive (dead) since Mon 2019-04-08 11:35:30 CEST; 1s ago
>      Docs: https://docs.docker.com
>   Process: 13714 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=0/SUCCESS)
>  Main PID: 13714 (code=exited, status=0/SUCCESS)
> 
> >Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.783450081+02:00" level=info msg="Loading containers: done."
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.882945376+02:00" level=info msg="Docker daemon" commit=d14af54 graphdriver(s)=overlay2 version=18.09.4
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.883023443+02:00" level=info msg="Daemon has completed initialization"
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.907022845+02:00" level=info msg="API listen on /var/run/docker.sock"
> Apr 08 11:34:39 tinyos systemd[1]: Started Docker Application Container Engine.
> Apr 08 11:35:30 tinyos systemd[1]: Stopping Docker Application Container Engine...
> Apr 08 11:35:30 tinyos dockerd[13714]: time="2019-04-08T11:35:30.224574738+02:00" level=info msg="Processing signal 'terminated'"
> Apr 08 11:35:30 tinyos dockerd[13714]: time="2019-04-08T11:35:30.226299525+02:00" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
> Apr 08 11:35:30 tinyos dockerd[13714]: time="2019-04-08T11:35:30.227150601+02:00" level=error msg="remove /var/run/docker.pid: no such file or directory"
> Apr 08 11:35:30 tinyos systemd[1]: Stopped Docker Application Container Engine.
> ```
> 
> Step 3:
> `sudo dockerd`
> 
> ```
> INFO[2019-04-08T11:35:44.909604039+02:00] parsed scheme: "unix"                         module=grpc
> INFO[2019-04-08T11:35:44.909617448+02:00] scheme "unix" not registered, fallback to default scheme  module=grpc
> INFO[2019-04-08T11:35:44.909647733+02:00] parsed scheme: "unix"                         module=grpc
> INFO[2019-04-08T11:35:44.909657202+02:00] scheme "unix" not registered, fallback to default scheme  module=grpc
> INFO[2019-04-08T11:35:44.909713390+02:00] ccResolverWrapper: sending new addresses to cc: [{unix:///run/containerd/containerd.sock 0  <nil>}]  module=grpc
> INFO[2019-04-08T11:35:44.909739132+02:00] ClientConn switching balancer to "pick_first"  module=grpc
> INFO[2019-04-08T11:35:44.910142846+02:00] pickfirstBalancer: HandleSubConnStateChange: 0xc42017abe0, CONNECTING  module=grpc
> INFO[2019-04-08T11:35:44.909722086+02:00] ccResolverWrapper: sending new addresses to cc: [{unix:///run/containerd/containerd.sock 0  <nil>}]  module=grpc
> INFO[2019-04-08T11:35:44.910200925+02:00] ClientConn switching balancer to "pick_first"  module=grpc
> INFO[2019-04-08T11:35:44.910504660+02:00] pickfirstBalancer: HandleSubConnStateChange: 0xc42017ad10, CONNECTING  module=grpc
> INFO[2019-04-08T11:35:44.910764106+02:00] pickfirstBalancer: HandleSubConnStateChange: 0xc42017abe0, READY  module=grpc
> INFO[2019-04-08T11:35:44.911108343+02:00] pickfirstBalancer: HandleSubConnStateChange: 0xc42017ad10, READY  module=grpc
> INFO[2019-04-08T11:35:44.910236232+02:00] blockingPicker: the picked transport is not ready, loop back to repick  module=grpc
> INFO[2019-04-08T11:35:44.912084762+02:00] [graphdriver] using prior storage driver: overlay2 
> INFO[2019-04-08T11:35:44.927898040+02:00] Graph migration to content-addressability took 0.00 seconds 
> WARN[2019-04-08T11:35:44.928256050+02:00] Your kernel does not support swap memory limit 
> WARN[2019-04-08T11:35:44.928307843+02:00] Your kernel does not support cgroup rt period 
> WARN[2019-04-08T11:35:44.928323493+02:00] Your kernel does not support cgroup rt runtime 
> INFO[2019-04-08T11:35:44.928811351+02:00] Loading containers: start.                   
> INFO[2019-04-08T11:35:45.207943761+02:00] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
> INFO[2019-04-08T11:35:45.319436873+02:00] Loading containers: done.                    
> INFO[2019-04-08T11:35:45.439639218+02:00] Docker daemon                                 commit=d14af54 graphdriver(s)=overlay2 version=18.09.4
> INFO[2019-04-08T11:35:45.439733271+02:00] Daemon has completed initialization          
> INFO[2019-04-08T11:35:45.464199779+02:00] API listen on /var/run/docker.sock
> ```
> 
> Hope this helps someone else.

@thanos1983 2 years later and your solution STILL worked for me, so thank you!

**Comment by pkesavap** [comment]
> I know this is an old question but just in case that someone might have the same problem here is what worked for me.
> 
> Step 1: `systemctl status docker`
> 
> If the docker is running you will get something like:
> 
> ```
> ● docker.service - Docker Application Container Engine
>    Loaded: loaded (/lib/systemd/system/docker.service; disabled; vendor preset: enabled)
>    Active: active (running) since Mon 2019-04-08 11:34:39 CEST; 33s ago
>      Docs: https://docs.docker.com
>  Main PID: 13714 (dockerd)
>     Tasks: 18
>    Memory: 34.2M
>    CGroup: /system.slice/docker.service
>            └─13714 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
> 
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.397942657+02:00" level=warning msg="Your kernel does not support swap memory limit"
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.397986822+02:00" level=warning msg="Your kernel does not support cgroup rt period"
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.397998384+02:00" level=warning msg="Your kernel does not support cgroup rt runtime"
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.398401944+02:00" level=info msg="Loading containers: start."
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.662918633+02:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to 
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.783450081+02:00" level=info msg="Loading containers: done."
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.882945376+02:00" level=info msg="Docker daemon" commit=d14af54 graphdriver(s)=overlay2 version=18.09.4
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.883023443+02:00" level=info msg="Daemon has completed initialization"
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.907022845+02:00" level=info msg="API listen on /var/run/docker.sock"
> Apr 08 11:34:39 tinyos systemd[1]: Started Docker Application Container Engine.
> ```
> 
> Step 2: `systemctl stop docker`
> 
> ```
> ● docker.service - Docker Application Container Engine
>    Loaded: loaded (/lib/systemd/system/docker.service; disabled; vendor preset: enabled)
>    Active: inactive (dead) since Mon 2019-04-08 11:35:30 CEST; 1s ago
>      Docs: https://docs.docker.com
>   Process: 13714 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=0/SUCCESS)
>  Main PID: 13714 (code=exited, status=0/SUCCESS)
> 
> >Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.783450081+02:00" level=info msg="Loading containers: done."
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.882945376+02:00" level=info msg="Docker daemon" commit=d14af54 graphdriver(s)=overlay2 version=18.09.4
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.883023443+02:00" level=info msg="Daemon has completed initialization"
> Apr 08 11:34:39 tinyos dockerd[13714]: time="2019-04-08T11:34:39.907022845+02:00" level=info msg="API listen on /var/run/docker.sock"
> Apr 08 11:34:39 tinyos systemd[1]: Started Docker Application Container Engine.
> Apr 08 11:35:30 tinyos systemd[1]: Stopping Docker Application Container Engine...
> Apr 08 11:35:30 tinyos dockerd[13714]: time="2019-04-08T11:35:30.224574738+02:00" level=info msg="Processing signal 'terminated'"
> Apr 08 11:35:30 tinyos dockerd[13714]: time="2019-04-08T11:35:30.226299525+02:00" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
> Apr 08 11:35:30 tinyos dockerd[13714]: time="2019-04-08T11:35:30.227150601+02:00" level=error msg="remove /var/run/docker.pid: no such file or directory"
> Apr 08 11:35:30 tinyos systemd[1]: Stopped Docker Application Container Engine.
> ```
> 
> Step 3: `sudo dockerd`
> 
> ```
> INFO[2019-04-08T11:35:44.909604039+02:00] parsed scheme: "unix"                         module=grpc
> INFO[2019-04-08T11:35:44.909617448+02:00] scheme "unix" not registered, fallback to default scheme  module=grpc
> INFO[2019-04-08T11:35:44.909647733+02:00] parsed scheme: "unix"                         module=grpc
> INFO[2019-04-08T11:35:44.909657202+02:00] scheme "unix" not registered, fallback to default scheme  module=grpc
> INFO[2019-04-08T11:35:44.909713390+02:00] ccResolverWrapper: sending new addresses to cc: [{unix:///run/containerd/containerd.sock 0  <nil>}]  module=grpc
> INFO[2019-04-08T11:35:44.909739132+02:00] ClientConn switching balancer to "pick_first"  module=grpc
> INFO[2019-04-08T11:35:44.910142846+02:00] pickfirstBalancer: HandleSubConnStateChange: 0xc42017abe0, CONNECTING  module=grpc
> INFO[2019-04-08T11:35:44.909722086+02:00] ccResolverWrapper: sending new addresses to cc: [{unix:///run/containerd/containerd.sock 0  <nil>}]  module=grpc
> INFO[2019-04-08T11:35:44.910200925+02:00] ClientConn switching balancer to "pick_first"  module=grpc
> INFO[2019-04-08T11:35:44.910504660+02:00] pickfirstBalancer: HandleSubConnStateChange: 0xc42017ad10, CONNECTING  module=grpc
> INFO[2019-04-08T11:35:44.910764106+02:00] pickfirstBalancer: HandleSubConnStateChange: 0xc42017abe0, READY  module=grpc
> INFO[2019-04-08T11:35:44.911108343+02:00] pickfirstBalancer: HandleSubConnStateChange: 0xc42017ad10, READY  module=grpc
> INFO[2019-04-08T11:35:44.910236232+02:00] blockingPicker: the picked transport is not ready, loop back to repick  module=grpc
> INFO[2019-04-08T11:35:44.912084762+02:00] [graphdriver] using prior storage driver: overlay2 
> INFO[2019-04-08T11:35:44.927898040+02:00] Graph migration to content-addressability took 0.00 seconds 
> WARN[2019-04-08T11:35:44.928256050+02:00] Your kernel does not support swap memory limit 
> WARN[2019-04-08T11:35:44.928307843+02:00] Your kernel does not support cgroup rt period 
> WARN[2019-04-08T11:35:44.928323493+02:00] Your kernel does not support cgroup rt runtime 
> INFO[2019-04-08T11:35:44.928811351+02:00] Loading containers: start.                   
> INFO[2019-04-08T11:35:45.207943761+02:00] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
> INFO[2019-04-08T11:35:45.319436873+02:00] Loading containers: done.                    
> INFO[2019-04-08T11:35:45.439639218+02:00] Docker daemon                                 commit=d14af54 graphdriver(s)=overlay2 version=18.09.4
> INFO[2019-04-08T11:35:45.439733271+02:00] Daemon has completed initialization          
> INFO[2019-04-08T11:35:45.464199779+02:00] API listen on /var/run/docker.sock
> ```
> 
> Hope this helps someone else.
2021 still works :)

**Comment by LucaErr** [comment]
not working

**Comment by LucaErr** [comment]
still getting the same massage :

Failure
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by thanos1983** [comment]
> still getting the same massage :
> 
> Failure Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Hello @LucaErr ,

Most likely your daemon is down. Check `systemctl status docker`. Without much of information I would suggest to follow this documentation [Post-installation steps for Linux](https://docs.docker.com/engine/install/linux-postinstall/).

I assume that you have installed correctly the packages and you have skipped by accident to enable it so on start up is not loading. Have you followed these steps [Configure Docker to start on boot](https://docs.docker.com/engine/install/linux-postinstall/#configure-docker-to-start-on-boot).

It should be fine after that.

Hope it helps.

BR / Thanos

**Comment by LucaErr** [comment]
@thanos1983 thanks for the reply, btw i resolved just with the latest version of docker... for a distraction mistake i installed a version not compatible with the latest version of rancher.
