### ISSUE TITLE
Docker crash on production, and restarts

### ISSUE THREAD

**Issue by marucjmar** [docker/for-linux#449]
* [x] This is a bug report
* [* ] I searched existing issues before opening this one

### Actual behavior
The docker daemon randomly stops.

**Output of `docker version`:**

```
Docker version 17.03.3-ce, build e19b718
```

**Output of `docker info`:**

```
Containers: 11
 Running: 4
 Paused: 0
 Stopped: 7
Images: 43
Server Version: 17.03.3-ce
Storage Driver: aufs
 Root Dir: /home/docker/aufs
 Backing Filesystem: extfs
 Dirs: 266
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: qxsmrf0e4alld5vk9abg4e2wi
 Is Manager: true
 ClusterID: mblhffi00vvjwopkdy6tdpsxq
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.0.60.11
 Manager Addresses:
  10.0.60.11:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6c463891b1ad274d505ae3bb738e530d1df2b3c7
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.854 GiB
Name: linux
ID: XG44:KZRS:XLCL:NMEZ:J6LC:K2S7:HS44:2SW7:XWZX:IWFJ:YCHF:NV4D
Docker Root Dir: /home/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**`cat /etc/resolv.conf`:**
```
domain local
search local
nameserver 10.0.60.2
#nameserver 111.212.51.18
```

**`cat  /etc/docker/daemon.json`:**
```
{
  "graph":"/home/docker"
}
```

**`sudo journalctl -l -u docker`:**
[Link to Logs](https://gist.github.com/marucjmar/1193dd9499d9473122026c9b2ce25421)

**Comment by thaJeztah** [comment]
Looks like your machine ran out of memory, which could lead to all kind of issues.


Note however, that Docker CE 17.03 reached EOL in June last year, and is no longer maintained; I'd recommend upgrading to a current version of docker.

Also keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because of the above, but feel free to continue the conversation
