### ISSUE TITLE
I have question only

### ISSUE THREAD

**Issue by monique77** [docker/for-linux#492]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Steps to reproduce the behavior

**Output of `docker version`:**
docker-ce version 18.03

```
(paste your output here)
```

**Output of `docker info`:**
My centos 7.4 not start after installacion docker 18.03 with kubernetes 1.v12

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
 Vmware 6.5

Tks so much

**Comment by thaJeztah** [comment]
Without more information, I don't think we'd be able to help. Do the logs show anything why docker doesn't start? Was this a new installation? Did docker start before you installed Kubernetes? Docker 18.03.0 CE has reached end of life; are you still seeing this on the current version?

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because of the above, but feel free to continue the conversation
