### ISSUE TITLE
Can't install docker-ce-cli on debian jessie: "Unable to locate package docker-ce-cli"

### ISSUE THREAD

**Issue by davidcsi** [docker/for-linux#633]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
install of docker-ce-cli

### Actual behavior
root@myhost:/home/admin# apt-get install docker-ce docker-ce-cli containerd.io
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package docker-ce-cli

### Steps to reproduce the behavior
on a fresh debian jessie follow:
https://docs.docker.com/install/linux/docker-ce/debian/

REMOVE SENSITIVE DATA BEFORE POSTING (replace those parts with "REDACTED")
-->

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment]
Jessie is no longer supported; see https://docs.docker.com/install/linux/docker-ce/debian/

But you should still be able to install Docker 18.06 (`docker-ce` package); be aware though that Docker 18.06 reached EOL, so won't receive future updates.

I'll close this ticket because it's not a big, but feel free to continue the conversation

**Comment by davidcsi** [comment]
oh wow, seems incredible with the jessie-installed base.
Ok thanks for the reply!
