### ISSUE TITLE
Communication problems between two containers using nginx

### ISSUE THREAD

**Issue by carlosafw** [docker/for-linux#676]
I have two containers. The first one runs nginx and serves static files

`-p 80:80 `
The second one runs a restful service

`-p 127.0.0.1:82:82;`

My front-end needs to request data from said service. I send my requests to localhost:82 and have the following proxy_pass configured on my nginx server:

```
server {
    listen 82;
    server_name front_go;

    location / {
        resolver 127.0.0.11;
        set $front "host.docker.internal:82";
        proxy_pass $front;
    }
}
```

Why does this setup works on my local windows machine but the connection is refused on my centos server?

**Comment by arkodg** [comment]
Hi @carlosafw 
`host.docker.internal` is a special DNS entry only available for MAC and Windows since for these cases `dockerd` runs inside a Linux VM
https://docs.docker.com/docker-for-mac/networking/)

You can use `--add-host` when running `dockerd` on the Linux host and not VM
https://docs.docker.com/engine/reference/commandline/run/#add-entries-to-container-hosts-file---add-host documents how you can use the --add-host argument to add entries to your container's /etc/hosts so something like `docker run --add-host=host.docker.internal:172.17.0.1 --rm -it alpine ping host.docker.internal` should help you reach the Linux host.

**Comment by carlosafw** [comment]
Hi @arkodg, thanks for the reply.

Running with the --add-host argument the container can now successfully ping my local bridge network, but I still couldn't get the proxy_pass to work, do you have any idea of what could it be?

**Comment by carlosafw** [comment]
I know this was a long time ago, just giving an update in case anyone else stumbles on this issue:

The host.docker.internal variable exists only in MAC and Windows enviroments
