### ISSUE TITLE
Debian Bullseye build missing

### ISSUE THREAD

**Issue by zimmi** [docker/for-linux#724]
* [ ] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

After the [release of Debian Buster on 2019-07-06](https://www.debian.org/News/2019/20190706), [Debian Bullseye](https://wiki.debian.org/DebianBullseye) is the current testing distribution. It would be nice to have a working repository and install instructions for `docker-ce` for Debian Bullseye.

**Comment by MichaIng** [comment]
@zimmi 
First Buster needs to be fully implemented: https://github.com/docker/docker-install/issues/125
The current version of get.docker.com does not even detect Debian Buster...

**Comment by zimmi** [comment]
[Using these scripts is not recommended for production environments](https://docs.docker.com/install/linux/docker-ce/debian/#install-using-the-convenience-script), so I don't think that should block adding the bullseye packages to the repository. Would still be nice, of course.

**Comment by MichaIng** [comment]
@zimmi 
As long as one does not understand why it is "not recommended for production environments", it is indeed the recommended install method. The warning applies to critical/professional servers where a professional admin knows what (s)he is doing and how to run the install steps fitting for the environment so that e.g. running processes are never disturbed or any local setup/settings broken 😉.

But yeah basically you are right, that adding additional branches to the repo is not tied to what the installer supports. However the state of Buster shows that it is not yet 100% integrated and there are still many bugs, e.g. on ARM Buster systems. So for now IMO testing should be focused on Buster to get this running stable on all architectures. Then one can thing about adding Bullseye.

**Comment by leighmcculloch** [comment]
Somehow my downloads for bullseye were working successfully until about an hour ago when I started seeing 404. If I just change the `lsbrelease -cs` part of the install instructions with `buster` it seems to work fine though as a work around. 🤔

**Comment by misterjoa** [comment]
`aufs-dkms` currently not installing on bullseye, incompatible kernel versions `5.2` vs. `5.4` currently in `bullseye`. I use the `buster` repo for docker (which used to work before).

**Comment by mherrmann** [comment]
Can confirm what @leighmcculloch wrote that the `buster` repository also works with `bullseye` (alpha 3).

**Comment by thaJeztah** [comment]
This should be fixed now
