### ISSUE TITLE
Docker Enterprise Edition Cookbook Integration Test

### ISSUE THREAD

**Issue by ckehoe** [docker/for-linux#80]
* [ ] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

We are developing an internal chef cookbook to configure Docker CE and EE. We don't have a need for Docker EE but would like to support the configuration for other teams in our organization that purchase a license and need to use it. The problem is that there doesn't appear to be a good way to integration test the section of the EE code without signing up for a trial (which expires in 1 month) or purchasing a license. We simply want a way to validate that our installation procedures without purchasing a license. It only needs to function in the sense that we can validate that the EE edition was installed and the docker cli functions as expected.

Questions:
1. If we sign up for the trial and it expires will the download and installation still function enough so that we can validate that the EE edition was installed?
2. Do you have other suggestions or workarounds for what we're trying to accomplish?

The feature request itself - if there isn't a viable workaround - is to use a different model for Docker EE installation. A potential model would be exposing the RPM download but require a license so we can validate that the installation procedures work as expected without having to have an account.

**Comment by thaJeztah** [comment]
To my knowledge, once installed, a docker-ee daemon/package will remain working (i.e., an active license is not actively enforced). This is just for the engine though, UCP and DTR may need a license.

If you need more information on those, it may be worth contacting support@docker.com

Let me close this issue here for housekeeping, but feel free to continue the conversation
