### ISSUE TITLE
unable to stop  zabbix-agent(can be any service like memcached etc) inside docker container using command service stop zabbix-agent stop

### ISSUE THREAD

**Issue by gkgaurav05** [docker/for-linux#818]
I have a docker container with multiple processes (running MySQL and Zabbix-agent). I am able to start zabbix-agent using "service zabbix-agent start" but unable to stop using "service zabbix-agent stop" command. To stop Zabbix-agent, I have to kill the processes of Zabbix. following are the process running. Is this issue inside the docker or something I need to do?

![zabbix](https://user-images.githubusercontent.com/20453781/66651188-0fe95700-ec50-11e9-8b90-b0a03f23cc9b.PNG)

**Comment by geo-mattrix** [comment]
did you tried :  killall zabbix_agentd

**Comment by thaJeztah** [comment]
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation
