### ISSUE TITLE
Slower in container than host

### ISSUE THREAD

**Issue by onexixi** [docker/for-linux#870]
* [x] This is a bug report
* [x] I searched existing issues before opening this one

when i do it 
  
 #   time for i in {1..1000000};do echo $[i*i] >/dev/null ;done

Slower in container than host
container 8.783s   host 7.720s 
   40cpus   Slower
i work ubuntu16.04
and  use  images ubuntu:16.04

**Comment by thaJeztah** [comment]
Not seeing a lot of difference:


on the host:

```bash
time for i in {1..1000000};do echo $[i*i] >/dev/null; done

real	0m13.139s
user	0m8.595s
sys	0m4.402s
```

Inside container

```bash
docker run --rm ubuntu:16.04 bash -c 'time for i in {1..1000000};do echo $[i*i] >/dev/null; done'

real	0m13.976s
user	0m8.020s
sys	0m5.755s
```

Possibly some overhead in the kernel due to the cgroups and security profiles set on the container; running the container with `--privileged` (which disables most of those) makes it slightly faster;

```bash
docker run --rm --privileged ubuntu:16.04 bash -c 'time for i in {1..1000000};do echo $[i*i] >/dev/null; done'

real	0m12.458s
user	0m7.822s
sys	0m4.429s
```

results when disabling seccomp profiles;

```bash
docker run --rm --security-opt seccomp=unconfined ubuntu:16.04 bash -c 'time for i in {1..1000000};do echo $[i*i] >/dev/null ;done'

real	0m12.974s
user	0m8.356s
sys	0m4.427s
```

Although it's not really conclusive because the results vary with +/- 500ms between runs.

I don't think Docker would be the culprit for the example you've given, given that no networking is used and no files are written to disk, so docker is not really between that (just the kernel).


I'm closing this issue for now, because I don't think there's something actionable here (at least not for the given example), but feel free to continue the conversation

**Comment by onexixi** [comment]
thanks  
we find  it like you said
When we use docker for biological information calculations, we should focus on those issues, please give us some suggestions or book names or blogs.
