### ISSUE TITLE
Changed docker image installation dir but give errors “Unable to open a folder for… No application is registered as handling this file” error

### ISSUE THREAD

**Issue by StefanMallia** [docker/for-linux#96]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
I've changed the directory of docker containers and images to an hdd (following Piotr Król's answer here: https://stackoverflow.com/a/34731550/4207050) to keep them off my ssd.
I now expect docker to function almost exactly the same but instead of using my ssd as a data directory, it should use my hdd.

### Actual behavior
But now I'm getting errors (sometimes these two error messages are displayed multiple times at once) about not being able to open folders as shown below when trying to build or run docker images. The images seem to build and run normally regardless of the error messages. What could be the cause for this and is there a fix?

### Steps to reproduce the behavior
Using docker-ce 17.06.1-ce package on debian buster/sid with linux kernel 4.12.01-amd64.
Follow these steps:
https://stackoverflow.com/a/34731550/4207050
Then, build or run a docker image/container.

Unable to open a folder for... 
![](https://i.stack.imgur.com/Y3nB0.png)
Mounts (the first two volumes are on the 238GB hdd, mnt/docker/plugins and mnt/docker/aufs)
![](https://i.stack.imgur.com/uTizD.png)

Posted to stack overflow as well (https://stackoverflow.com/questions/45983774/changed-docker-image-installation-dir-but-give-errors-unable-to-open-a-folder-f)

**Comment by thaJeztah** [comment]
This doesn't look like a bug in Docker; what I suspect is happening is that something on your system is registered to auto-play or open/scan/create previews for files when a device is attached to your computer.

If you're using device mapper, each container mounts a new device on your computer for the root-filesystem of the container. Apparently that triggers the software on your computer to attempt to _open_ the device, which fails.

Searching for `"No application is registered as handling this file"` on Google shows quite some results; possibly one of those may provide more information on how to disable that functionality, or exclude certain paths from being handled.

I'm closing this issue, because this is not a bug in docker, but a configuration issue on your machine. Feel free to comment though after I closed
