### ISSUE TITLE
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown

### ISSUE THREAD

**Issue by AkulaRushikesh** [docker/for-linux#963]
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown

I am facing this issue,
I have this in my $PATH

/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin

_Originally posted by @AkulaRushikesh in https://github.com/docker/for-linux/issues/246#issuecomment-605391907_

**Comment by thaJeztah** [comment]
This error occurs if the executable was not found inside the container (so the `$PATH` on your host is not relevant here).

Without information about the container / image you're running, there's not much to tell, but most likely, the container does not have `bash` installed (you can try running `sh` instead of `bash` -  `docker exec -it <your container> sh`), or if it's a minimal image, the container may not have a shell installed at all (in which case you can't use `docker exec` to get a shell).


This doesn't look like a bug, and without more details, this ticket is not actionable, so I'm closing it. Feel free to continue the conversation after I closed though.

**Comment by eman602** [comment]
Using the docker command `docker exec -it <your container> sh` will allow you to overcome the issue. It does appear that bash is not installed in the container.

**Comment by crgbe** [comment]
You saved my evening, thanks

**Comment by feirychris** [comment]
Thank you, it worked for me

**Comment by sivasankaran96** [comment]
thanks gyus
