### ISSUE TITLE
docker build with chmod make image bigger than without chmod

### ISSUE THREAD

**Issue by lovebaby979** [docker/for-linux#964]
**Dockerfile without chmod：**

FROM  alpine:3.10
COPY csf-controllers /csf-controllers
RUN chmod +x /csf-controllers

csf-controllers size: 44MB
alpine:3.10 size: 7.03MB

build command：docker build -t myImage:1.0

**in this case, myImage:1.0 size is 51.03MB**

**Dockerfile with chmod：**

FROM  alpine:3.10
COPY csf-controllers /csf-controllers
RUN chmod +x /csf-controllers

build command：docker build -t myImage:1.0

**in this case, myImage:1.0 size is 85.03MB**

why size diffrent?

**Comment by cpuguy83** [comment]
The chmod triggers a copy-up. So the binary is in the layer chain twice. One for the initial "COPY", and one for the chmod'd version.
This is how copy-on-write works, it's just unfortunate that overlay handles it this way.

This is dependent on the file system being used.
I recall overlayfs has a setting which allows metadata only (e.g. chmod) changes without a copy-up, but I have not tested it, and there were bugs in the kernel with it in the past.

To try you'll want to enable metacopy: https://github.com/amir73il/overlayfs/wiki/Overlayfs-overview

Closing as this is expected behavior, but feel free to discuss.
