### ISSUE TITLE
Freshly installed docker: Error while running Hello-world

### ISSUE THREAD

**Issue by xabierolaz** [docker/for-linux#991]
Cannot get docker's **Hello-world** to work in a new system
Using ubuntu 18.04
```
sudo apt-get update
sudo apt install docker.io
sudo systemctl start docker
sudo systemctl enable docker
docker --version
docker run hello-world
sudo docker run hello-world
```

Output:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/overlay2/bda2dea2f192841f195b970c6c955f5df6acbda36cf5dee3c9c532271c7ca8bb/merged\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown.
ERRO[0000] error waiting for container: context canceled 
`

**Comment by thaJeztah** [comment]
The `docker.io` package is not the official docker package, but a package built by the Ubuntu package maintainers. Are you having the same problem when installing the official packages (as outlined in https://docs.docker.com/engine/install/ubuntu/)?

I'm closing this issue because of the above, but feel free to continue the conversation
